sudo: required

services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.11.2-0~trusty

before_install:
  - apt-cache madison docker-engine
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - docker version
  - docker info
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -y
  - sudo apt-get install -y bats

script:
  - docker build -t hrektts/ros2:bats .
  - travis_wait 50 bats test
